#############################################################################
# Makefile for building: MPControl
# Generated by qmake (2.01a) (Qt 4.7.3) on: do 2. mei 18:39:16 2013
# Project:  MPControl.pro
# Template: app
# Command: c:\qtsdk\symbian\sdks\symbian1qt473\bin\qmake.exe -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc -o bld.inf MPControl.pro
#############################################################################

MAKEFILE          = Makefile
QMAKE             = c:\qtsdk\symbian\sdks\symbian1qt473\bin\qmake.exe
DEL_FILE          = del 2> NUL
DEL_DIR           = rmdir
MOVE              = move
CHK_DIR_EXISTS    = if not exist
MKDIR             = mkdir
XCOPY             = xcopy /d /f /h /r /y /i
ABLD              = ABLD.BAT
DEBUG_PLATFORMS   = winscw gcce armv5 armv6
RELEASE_PLATFORMS = gcce armv5 armv6
MAKE              = make

ifeq (WINS,$(findstring WINS, $(PLATFORM)))
ZDIR=$(EPOCROOT)epoc32\release\$(PLATFORM)\$(CFG)\z
else
ZDIR=$(EPOCROOT)epoc32\data\z
endif

DEFINES	 = -DSYMBIAN -DUNICODE -DQT_KEYPAD_NAVIGATION -DQT_SOFTKEYS_ENABLED -DQT_USE_MATH_H_FLOATS -DQT_GUI_LIB -DQT_CORE_LIB
INCPATH	 =  -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtCore" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtCore/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtGui" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/QtGui/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/include/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/mkspecs/common/symbian" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/mkspecs/common/symbian/tmp" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions/stdapis" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions/stdapis/sys" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/stdapis" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/stdapis/sys" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions/stdapis/stlport" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/stdapis/stlport" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/oem" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/middleware" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/domain/middleware" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/osextensions" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/domain/osextensions" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/domain/osextensions/loc" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/domain/middleware/loc" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/domain/osextensions/loc/sc" -I"C:/QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/include/domain/middleware/loc/sc" -I"C:/Users/Steven/Desktop/Git/MPControl/moc" -I"C:/Users/Steven/Desktop/Git/MPControl/moc/tmp" -I"C:/Users/Steven/Desktop/Git/MPControl/ui" -I"C:/Users/Steven/Desktop/Git/MPControl/ui/tmp" -I"C:/Users/Steven/Desktop/Git/MPControl" -I"C:/Users/Steven/Desktop/Git/MPControl/tmp"
first: default
default: debug-winscw
all: debug release

qmake:
	$(QMAKE) "C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

bld.inf: C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro
	$(QMAKE) "C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

$(ABLD): bld.inf
	bldmake bldfiles

c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc: 
	$(QMAKE) "C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro"  -spec c:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\symbian-abld -after  OBJECTS_DIR=obj MOC_DIR=moc UI_DIR=ui RCC_DIR=rcc

debug: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build winscw udeb
	$(ABLD) build gcce udeb
	$(ABLD) build armv5 udeb
	$(ABLD) build armv6 udeb

release: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build gcce urel
	$(ABLD) build armv5 urel
	$(ABLD) build armv6 urel

debug-winscw: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build winscw udeb
debug-gcce: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build gcce udeb
debug-armv5: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build armv5 udeb
debug-armv6: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build armv6 udeb
release-gcce: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build gcce urel
release-armv5: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build armv5 urel
release-armv6: c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc $(ABLD)
	$(ABLD) build armv6 urel

export: $(ABLD)
	$(ABLD) export

cleanexport: $(ABLD)
	$(ABLD) cleanexport

check: first

${ZDIR}\resource\apps\MPControl.mif: MPControl.svg
	mifconv ${ZDIR}\resource\apps\MPControl.mif /c32 MPControl.svg

run:
	call /QtSDK/Symbian/SDKs/Symbian1Qt473/epoc32/release/winscw/udeb/MPControl.exe $(QT_RUN_OPTIONS)

runonphone: sis
	runonphone $(QT_RUN_ON_PHONE_OPTIONS) --sis MPControl.sis MPControl.exe $(QT_RUN_OPTIONS)

MPControl_template.pkg: C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro
	$(MAKE) -f $(MAKEFILE) qmake

MPControl_installer.pkg: C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro
	$(MAKE) -f $(MAKEFILE) qmake

MPControl_stub.pkg: C:/Users/Steven/Desktop/Git/MPControl/MPControl.pro
	$(MAKE) -f $(MAKEFILE) qmake

sis: MPControl_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_sis:
	createpackage $(QT_SIS_OPTIONS) MPControl_template.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_sis: MPControl_template.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_unsigned_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_unsigned_sis:
	createpackage $(QT_SIS_OPTIONS) -o MPControl_template.pkg $(QT_SIS_TARGET)

MPControl.sis:
	$(MAKE) -f $(MAKEFILE) sis

installer_sis: MPControl_installer.pkg sis
	$(MAKE) -f $(MAKEFILE) ok_installer_sis

ok_installer_sis: MPControl_installer.pkg
	createpackage $(QT_SIS_OPTIONS) MPControl_installer.pkg - $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

unsigned_installer_sis: MPControl_installer.pkg unsigned_sis
	$(MAKE) -f $(MAKEFILE) ok_unsigned_installer_sis

ok_unsigned_installer_sis: MPControl_installer.pkg
	createpackage $(QT_SIS_OPTIONS) -o MPControl_installer.pkg

fail_sis_nocache:
	$(error Project has to be built or QT_SIS_TARGET environment variable has to be set before calling 'SIS' target)

stub_sis: MPControl_stub.pkg
	$(if $(wildcard .make.cache), $(MAKE) -f $(MAKEFILE) ok_stub_sis MAKEFILES=.make.cache , $(if $(QT_SIS_TARGET), $(MAKE) -f $(MAKEFILE) ok_stub_sis , $(MAKE) -f $(MAKEFILE) fail_sis_nocache ) )

ok_stub_sis:
	createpackage -s $(QT_SIS_OPTIONS) MPControl_stub.pkg $(QT_SIS_TARGET) $(QT_SIS_CERTIFICATE) $(QT_SIS_KEY) $(QT_SIS_PASSPHRASE)

store_build:
	@echo # ============================================================================== > .make.cache && echo # This file is generated by make and should not be modified by the user >> .make.cache && echo # Name : .make.cache >> .make.cache && echo # Part of : lineedits >> .make.cache && echo # Description : This file is used to cache last build target for >> .make.cache && echo # make sis target. >> .make.cache && echo # Version : >> .make.cache && echo # >> .make.cache && echo # ============================================================================== >> .make.cache && echo QT_SIS_TARGET ?= $(QT_SIS_TARGET) >> .make.cache

deploy: sis
	call MPControl.sis

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc\moc_remoteui.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc\moc_remoteui.cpp
moc\moc_remoteui.cpp: remoteui.h
	C:\QtSDK\Symbian\SDKs\Symbian1Qt473\bin\moc.exe $(DEFINES) $(INCPATH) -DSYMBIAN remoteui.h -o moc\moc_remoteui.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: ui\qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) ui\qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui\ui_remoteui.h
compiler_uic_clean:
	-$(DEL_FILE) ui\ui_remoteui.h
ui\ui_remoteui.h: remoteui.ui
	c:\QtSDK\Symbian\SDKs\Symbian1Qt473\bin\uic.exe remoteui.ui -o ui\ui_remoteui.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_uic_clean 

create_temps:
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtGui\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtGui\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp"
	-@ if not exist "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp" mkdir "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp"
	-@ if not exist "C:\Users\Steven\Desktop\Git\MPControl\moc\tmp" mkdir "C:\Users\Steven\Desktop\Git\MPControl\moc\tmp"
	-@ if not exist "C:\Users\Steven\Desktop\Git\MPControl\ui\tmp" mkdir "C:\Users\Steven\Desktop\Git\MPControl\ui\tmp"
	-@ if not exist "C:\Users\Steven\Desktop\Git\MPControl\tmp" mkdir "C:\Users\Steven\Desktop\Git\MPControl\tmp"

extension_clean: compiler_clean
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtCore\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtGui\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\QtGui\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\include\tmp"
	-@ if EXIST "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp" rmdir /s /q  "C:\QtSDK\Symbian\SDKs\Symbian1Qt473\mkspecs\common\symbian\tmp"
	-@ if EXIST "C:\Users\Steven\Desktop\Git\MPControl\moc\tmp" rmdir /s /q  "C:\Users\Steven\Desktop\Git\MPControl\moc\tmp"
	-@ if EXIST "C:\Users\Steven\Desktop\Git\MPControl\ui\tmp" rmdir /s /q  "C:\Users\Steven\Desktop\Git\MPControl\ui\tmp"
	-@ if EXIST "C:\Users\Steven\Desktop\Git\MPControl\tmp" rmdir /s /q  "C:\Users\Steven\Desktop\Git\MPControl\tmp"

pre_targetdeps: \
	generated_sources \
	all_source_deps \
	${ZDIR}\resource\apps\MPControl.mif \
	ui\ui_remoteui.h

generated_sources: \
	moc\moc_remoteui.cpp

all_source_deps: \
	remoteui.h \
	ui\ui_remoteui.h

finalize:

winscw_deployment:

winscw_deployment_clean:

deployment:

deployment_clean:

dodistclean:
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl_template.pkg" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl_template.pkg"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl_stub.pkg" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl_stub.pkg"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl_installer.pkg" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl_installer.pkg"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\Makefile" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\Makefile"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\Makefile_MPControl_exe.mk" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\Makefile_MPControl_exe.mk"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl_exe.mmp" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl_exe.mmp"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl_reg.rss" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl_reg.rss"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl.rss" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl.rss"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\MPControl.loc"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\bld.inf" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\bld.inf"
	-@ if EXIST "c:\Users\Steven\Desktop\Git\MPControl\${ZDIR}\resource\apps\MPControl.mif" $(DEL_FILE)  "c:\Users\Steven\Desktop\Git\MPControl\${ZDIR}\resource\apps\MPControl.mif"

distclean: clean dodistclean

clean: $(ABLD)
	-$(ABLD) reallyclean
	-bldmake clean

clean-debug: $(ABLD)
	$(ABLD) reallyclean winscw udeb
	$(ABLD) reallyclean gcce udeb
	$(ABLD) reallyclean armv5 udeb
	$(ABLD) reallyclean armv6 udeb

clean-release: $(ABLD)
	$(ABLD) reallyclean gcce urel
	$(ABLD) reallyclean armv5 urel
	$(ABLD) reallyclean armv6 urel

clean-debug-winscw: $(ABLD)
	$(ABLD) reallyclean winscw udeb
clean-debug-gcce: $(ABLD)
	$(ABLD) reallyclean gcce udeb
clean-debug-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 udeb
clean-debug-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 udeb
clean-release-gcce: $(ABLD)
	$(ABLD) reallyclean gcce urel
clean-release-armv5: $(ABLD)
	$(ABLD) reallyclean armv5 urel
clean-release-armv6: $(ABLD)
	$(ABLD) reallyclean armv6 urel

freeze: $(ABLD)
	$(ABLD) freeze

freeze-debug: freeze

freeze-release: freeze

freeze-debug-winscw: $(ABLD)
	$(ABLD) freeze winscw
freeze-debug-gcce: $(ABLD)
	$(ABLD) freeze gcce
freeze-debug-armv5: $(ABLD)
	$(ABLD) freeze armv5
freeze-debug-armv6: $(ABLD)
	$(ABLD) freeze armv6
freeze-release-gcce: $(ABLD)
	$(ABLD) freeze gcce
freeze-release-armv5: $(ABLD)
	$(ABLD) freeze armv5
freeze-release-armv6: $(ABLD)
	$(ABLD) freeze armv6

